#!/usr/bin/env ruby

$LOAD_PATH << "lib"
$LOAD_PATH << "models"

require 'environment'
Environment.environment = ENV["ENVIRONMENT"] || "production"
$stderr = $stdout

require 'account'

def menu
<<EOS
What do you want to do?
1. Add Account
2. Update Monthly Income
3. Can I Get This Car?
EOS
end

def set_monthly_income_for(account)
  puts "What is the new monthly income for #{account.name}?"
  new_monthly_income = gets
  return unless new_monthly_income
  new_monthly_income.chomp!
  account.update(new_monthly_income)
end

def add_account
  puts "Who's account will this be?"
  account_name = gets
  return unless account_name
  account_name.chomp!
  account = Account.new(account_name)
  if account.save
    puts "#{account.name} has been added."
    set_monthly_income_for(account)
  else
    puts account.errors
    add_account
  end
end

def update_monthly_income
  puts "Who's account do you want to update?"
  account_name = gets
  return unless account_name
  account_name.chomp!
  account = Account.find_by_name(account_name)
  if account
    set_monthly_income_for(account)
  else
    puts account.errors
    update_monthly_income
  end
end

def car_choice
  puts "What car do you want to buy?"
end

def get_menu_selection
  puts menu
  input = gets
  return unless input
  input.chomp!
  if input == "1"
    add_account
  elsif input == "2"
    update_monthly_income
  elsif input == "3"
    car_choice
  else
    puts "'#{input}' is not a valid selection"
    get_menu_selection
  end
end

get_menu_selection
